const BLOG_CATEGORIES = [
 "Technology",
  "Programming",
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Cloud Computing",
  "DevOps",
  "Software Engineering",
  "UI/UX Design",
  "Productivity",
  "Education",
  "Career Development",
  "Business",
  "Startups",
  "Entrepreneurship",
  "Marketing",
  "Finance",
  "Investing",
  "Cryptocurrency",
  "E-commerce",
  "Health",
  "Fitness",
  "Nutrition",
  "Mental Health",
  "Lifestyle",
  "Travel",
  "Food",
  "Cooking",
  "Fashion",
  "Beauty",
  "Personal Development",
  "Motivation",
  "Self Improvement",
  "Photography",
  "Art",
  "Music",
  "Movies",
  "Books",
  "Gaming",
  "Sports",
  "Science",
  "Environment",
  "Politics",
  "News",
  "Parenting",
  "Relationships",
  "Spirituality",
  "History",
  "Culture",
  "Other",
];
export default BLOG_CATEGORIES;